name: gsb_new_app
description: "Sport quiz app"
publish_to: 'none'
version: 1.2.4+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.3.0
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.6.0
  webview_flutter: ^4.8.0
  firebase_remote_config: ^5.0.4
  google_fonts: ^6.2.1
  onesignal_flutter: ^5.2.6
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1




flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/


flutter_launcher_icons:
      android: "launcher_icon"
      ios: true
      remove_alpha_ios: true
      image_path: "assets/icon.png"
      min_sdk_android: 24 # android min sdk min:16, default 21
      adaptive_icon_background: "#ffffff" # You can use a color or image for the background
      adaptive_icon_foreground: "assets/icon.png" # For adaptive icons on Android

flutter_native_splash:
  color: "#e3e3e3"
  image: assets/icon.png
  android_12: 
    image: assets/icon.png
    color: "#e3e3e3"
 